import placeholderData from './placeholder-images.json';
import type { Content } from './types';

const getImage = (id: string) => {
  const image = placeholderData.placeholderImages.find((img) => img.id === id);
  if (!image) {
    throw new Error(`Image with id "${id}" not found.`);
  }
  return image;
};

export const contentData: Content[] = [
  {
    id: 'demon-slayer',
    title: 'Demon Slayer: Kimetsu no Yaiba',
    description: 'A young man becomes a demon slayer after his family is slaughtered and his younger sister is turned into a demon.',
    type: 'anime',
    genre: ['Action', 'Fantasy', 'Adventure'],
    year: 2019,
    rating: 8.7,
    duration: '24 min',
    tags: ['demons', 'sword fight', 'historical', 'supernatural'],
    poster: getImage('poster-demon-slayer'),
    thumbnail: getImage('thumb-demon-slayer'),
    hero: getImage('hero-demon-slayer'),
  },
  {
    id: 'jujutsu-kaisen',
    title: 'Jujutsu Kaisen',
    description: 'A boy swallows a cursed talisman - the finger of a demon - and becomes cursed himself. He enters a shaman\'s school to be able to locate the demon\'s other body parts and thus exorcise himself.',
    type: 'anime',
    genre: ['Action', 'Supernatural', 'Dark Fantasy'],
    year: 2020,
    rating: 8.6,
    duration: '24 min',
    tags: ['sorcery', 'curses', 'urban fantasy', 'school life'],
    poster: getImage('poster-jujutsu-kaisen'),
    thumbnail: getImage('thumb-jujutsu-kaisen'),
    hero: getImage('hero-jujutsu-kaisen'),
  },
  {
    id: 'attack-on-titan',
    title: 'Attack on Titan',
    description: 'After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.',
    type: 'anime',
    genre: ['Action', 'Dark Fantasy', 'Post-Apocalyptic'],
    year: 2013,
    rating: 9.0,
    duration: '24 min',
    tags: ['titans', 'dystopian', 'military', 'survival horror'],
    poster: getImage('poster-attack-on-titan'),
    thumbnail: getImage('thumb-attack-on-titan'),
    hero: getImage('hero-attack-on-titan'),
  },
  {
    id: 'your-name',
    title: 'Your Name',
    description: 'Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?',
    type: 'anime',
    genre: ['Romance', 'Fantasy', 'Drama'],
    year: 2016,
    rating: 8.4,
    duration: '1h 46m',
    tags: ['body swapping', 'comet', 'love story', 'slice of life'],
    poster: getImage('poster-your-name'),
    thumbnail: getImage('thumb-your-name'),
    hero: getImage('hero-your-name'),
  },
  {
    id: 'spirited-away',
    title: 'Spirited Away',
    description: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    type: 'anime',
    genre: ['Fantasy', 'Adventure', 'Family'],
    year: 2001,
    rating: 8.6,
    duration: '2h 5m',
    tags: ['Studio Ghibli', 'spirits', 'coming-of-age', 'folklore'],
    poster: getImage('poster-spirited-away'),
    thumbnail: getImage('thumb-spirited-away'),
    hero: getImage('hero-spirited-away'),
  },
  {
    id: 'inception',
    title: 'Inception',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    type: 'movie',
    genre: ['Sci-Fi', 'Action', 'Thriller'],
    year: 2010,
    rating: 8.8,
    duration: '2h 28m',
    tags: ['dreams', 'heist', 'mind-bending', 'psychological'],
    poster: getImage('poster-inception'),
    thumbnail: getImage('thumb-inception'),
    hero: getImage('hero-inception'),
  },
  {
    id: 'interstellar',
    title: 'Interstellar',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    type: 'movie',
    genre: ['Sci-Fi', 'Adventure', 'Drama'],
    year: 2014,
    rating: 8.6,
    duration: '2h 49m',
    tags: ['space travel', 'wormhole', 'dystopian', 'relativity'],
    poster: getImage('poster-interstellar'),
    thumbnail: getImage('thumb-interstellar'),
    hero: getImage('hero-interstellar'),
  },
  {
    id: 'blade-runner-2049',
    title: 'Blade Runner 2049',
    description: 'Young Blade Runner K\'s discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who\'s been missing for thirty years.',
    type: 'movie',
    genre: ['Sci-Fi', 'Thriller', 'Mystery'],
    year: 2017,
    rating: 8.0,
    duration: '2h 44m',
    tags: ['cyberpunk', 'neo-noir', 'artificial intelligence', 'dystopian'],
    poster: getImage('poster-blade-runner'),
    thumbnail: getImage('thumb-blade-runner'),
    hero: getImage('hero-blade-runner'),
  },
  {
    id: 'dune',
    title: 'Dune',
    description: 'Feature adaptation of Frank Herbert\'s science fiction novel, about the son of a noble family entrusted with the protection of the most valuable asset and most vital element in the galaxy.',
    type: 'movie',
    genre: ['Sci-Fi', 'Adventure', 'Drama'],
    year: 2021,
    rating: 8.0,
    duration: '2h 35m',
    tags: ['space opera', 'feudalism', 'desert planet', 'prophecy'],
    poster: getImage('poster-dune'),
    thumbnail: getImage('thumb-dune'),
    hero: getImage('hero-dune'),
  },
  {
    id: 'parasite',
    title: 'Parasite',
    description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    type: 'movie',
    genre: ['Thriller', 'Comedy', 'Drama'],
    year: 2019,
    rating: 8.5,
    duration: '2h 12m',
    tags: ['social satire', 'dark comedy', 'class struggle', 'suspense'],
    poster: getImage('poster-parasite'),
    thumbnail: getImage('thumb-parasite'),
    hero: getImage('hero-parasite'),
  },
];
