// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.
import { useState, useEffect } from "react";
import { onAuthStateChanged, type User } from "firebase/auth";
import { useAuth } from "../provider";

export function useUser() {
  const auth = useAuth();
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(
      auth,
      (user) => {
        setUser(user);
        setLoading(false);
      },
      (err) => {
        setError(err);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [auth]);

  return { user, loading, error };
}
