// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.
import { useState, useEffect } from "react";
import {
  onSnapshot,
  collection,
  query,
  where,
  type Firestore,
  type CollectionReference,
  type Query,
} from "firebase/firestore";
import { useFirestore } from "../provider";

interface UseCollectionOptions {
  where?: [string, "==", string];
}

export function useCollection<T>(
  collectionName: string,
  options?: UseCollectionOptions
) {
  const firestore = useFirestore();
  const [data, setData] = useState<T[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    let q: Query | CollectionReference = collection(
      firestore,
      collectionName
    );

    if (options?.where) {
      q = query(q, where(options.where[0], options.where[1], options.where[2]));
    }

    const unsubscribe = onSnapshot(
      q,
      (snapshot) => {
        const result: T[] = [];
        snapshot.forEach((doc) => {
          result.push({ id: doc.id, ...doc.data() } as T);
        });
        setData(result);
        setLoading(false);
      },
      (err) => {
        setError(err);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [firestore, collectionName, options?.where?.[0], options?.where?.[1], options?.where?.[2]]);

  return { data, loading, error };
}
