// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.
"use client";
import { FirebaseProvider } from "./provider";

export const FirebaseClientProvider: React.FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  return <FirebaseProvider>{children}</FirebaseProvider>;
};
