// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.
// Your project's Firebase configuration.
export const firebaseConfig = {
  apiKey: "AIzaSyDDHVT6HXyYF8907s1yev4x2xw78fze3So",
  authDomain: "studio-8033237225-86c69.firebaseapp.com",
  projectId: "studio-8033237225-86c69",
  storageBucket: "studio-8033237225-86c69.appspot.com",
  messagingSenderId: "525305115123",
  appId: "1:525305115123:web:a9cb90653aaa30682b6286"
};
